import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/contexts/provider/ThemeProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "@/assets/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body
            className={`
              ${geistSans.variable} 
              ${geistMono.variable} 
              antialiased
            `}
          >
            {/* navbar */}
            <div
              className="
                w-full bg-white px-4
                md:px-8 lg:px-16 xl:px-32 2xl:px-64">
              <Navbar />
            </div>
          
            {/* main content */}
            <div
              className="
                bg-slate-100 px-4
                md:px-8 lg:px-16 xl:px-32 2xl:px-64
                min-h-screen">
              {children}
            </div>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
