import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Background from "@/components/Background";
import { ThemeProvider } from "@/contexts/provider/ThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body
            className={`
              antialiased
            `}
          >
            {/* background */}
            <div className="absolute">
              <Background />
            </div>

            {/* navbar */}
            <Navbar />
          
            {/* main content */}
            <div
              className="
                bg-slate-100/50 px-4
                md:px-8 lg:px-16 xl:px-32 2xl:px-64
                min-h-[calc(100vh-96px)] relative
              ">    
              {children}
            </div>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
